# Where things are
source:       .
destination:  ./_site
plugins:      ./_plugins
layouts:      ./_layouts
paginate:     8

# Handling Reading
safe:         false
include:      [".htaccess"]
exclude:      []
keep_files:   [".git", ".svn"]
encoding:     "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
textile_ext:  "textile"

# Filtering Content
show_drafts:  null
limit_posts:  0
future:       true
unpublished:  false

# Conversion
markdown:     Redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "strikethrough", "underline", "autolink", "tables", "with_toc_data"]
highlighter:  pygments
lsi:          false
#excerpt_separator: "\n\n"

# Serving
detach:       false
port:         4000
host:         127.0.0.1
baseurl:      "" # does not include hostname

# Outputting
permalink:     /:year/:month/:title
paginate_path: /page:num
timezone:      null


#Site config
title: 静静的博客
description: 一个销售的自我修养.
keywords: Blog 静静 知识 煤炭 软件 
url: http://jingjing.myrsoft.net
feed: /atom.xml
favicon: http://jekyllrb.com/favicon.png

#Nav config
nav:
  - text: 首页
    url: /index.html
  - text: 分类目录 
    url: /categories.html
  - text: 文章归档
    url: /archives.html
  - text: 关于我
    url: /about.html
  - text: 友情链接
    url: /links.html

#Author config
author:
    name: 静静
    email: jing_net@126.com
    imageLink: http://cn.gravatar.com/userimage/79086784/7a3d844a5f4a7d12edfb44f3139df32a.jpg?size=200
    simpleIntro: 我是「静静」，一个静静哈哈哈...
    detailIntro:
      <p>我建立这个博客的目的是... ...</p>
      <p>我的博客上主要分享的内容... ...</p>

#Follow me, you can choose your icon by http://fortawesome.github.io/Font-Awesome/icons/#brand
follow:
  - class: icon-rss
    url: /atom.xml
  - class: icon-weibo
    url: http://weibo.com/u/2230360055
  - class: icon-github-alt
    url: https://github.com/niutianjing
  - class: icon-twitter
    url: http://twitter.com
  - class: icon-google-plus
    url: http://google.com

#Links
customLinks:
  - item:
    - text: 掌心
      url: http://www.zhanxin.info
    message: Friends
  - item:
    - text: git 使用简易指南
      url: http://www.bootcss.com/p/git-guide/
    - text: Markdown 语法说明
      url: http://wowubuntu.com/markdown/
    message: 其他链接

#googleAnaly, your id link UA-12345678-X
googleAnaly:
  config: false
  id: UA-40169250-1

#comment config
disqus:
  config: false
  id: piznblog

duoshuo:
  config: true
  id: niujingjing